/*
 * Copyright (c) 2002-2020, City of Paris
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  1. Redistributions of source code must retain the above copyright notice
 *     and the following disclaimer.
 *
 *  2. Redistributions in binary form must reproduce the above copyright notice
 *     and the following disclaimer in the documentation and/or other materials
 *     provided with the distribution.
 *
 *  3. Neither the name of 'Mairie de Paris' nor 'Lutece' nor the names of its
 *     contributors may be used to endorse or promote products derived from
 *     this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * License 1.0
 */
package fr.paris.lutece.plugins.seo.web;

import fr.paris.lutece.plugins.seo.service.sitemap.SitemapService;
import fr.paris.lutece.portal.service.util.AppLogService;

import java.io.File;
import java.io.IOException;
import java.io.OutputStream;

import java.nio.file.Files;

import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 * Serves the sitemap generated by {@link SitemapService}.
 *
 * <p>
 * The sitemap is written outside the webapp, so no servlet container serves it : the webapp is a build artefact, replaced
 * at every deployment, and a generated file kept there is lost. This servlet is what publishes it, and the rewrite rules
 * of the plugin expose it on <code>/sitemap-seo.xml</code>, the path to declare in the <code>Sitemap</code> directive of
 * <code>robots.txt</code>.
 * </p>
 */
public class SitemapServlet extends HttpServlet
{
    private static final long serialVersionUID = 1L;
    private static final String CONTENT_TYPE = "application/xml;charset=UTF-8";

    /**
     * Writes the sitemap to the response, generating it when the file is not there yet : the daemon may not have run on
     * this node, and the default directory does not survive a restart.
     *
     * {@inheritDoc}
     */
    @Override
    protected void doGet( HttpServletRequest request, HttpServletResponse response ) throws ServletException, IOException
    {
        File fileSitemap = SitemapService.getSitemapFile( );

        if ( !fileSitemap.isFile( ) )
        {
            AppLogService.info( "SEO : {} is not there yet, generating the sitemap on demand", fileSitemap );
            SitemapService.generateSitemap( );
        }

        if ( !fileSitemap.isFile( ) )
        {
            AppLogService.error( "SEO : the sitemap could not be generated, {} is still missing", fileSitemap );
            response.sendError( HttpServletResponse.SC_NOT_FOUND );

            return;
        }

        response.setContentType( CONTENT_TYPE );
        response.setContentLengthLong( fileSitemap.length( ) );
        response.setDateHeader( "Last-Modified", fileSitemap.lastModified( ) );

        try ( OutputStream out = response.getOutputStream( ) )
        {
            Files.copy( fileSitemap.toPath( ), out );
        }
    }
}
